<a href="https://colab.research.google.com/github/faique1234/Working-with-numpy/blob/main/Working_with_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to numpy

### Subtask:
Briefly explain what NumPy is and its importance in numerical computing in Python.


**Reasoning**:
Add a markdown cell at the beginning of the notebook to provide a brief explanation of NumPy and its importance in numerical computing.



In [2]:
import numpy as np

# Create a NumPy array from a Python list
array_from_list = np.array([1, 2, 3, 4, 5])

# Create a NumPy array of zeros
zeros_array = np.zeros((3, 4))

# Create a NumPy array of ones
ones_array = np.ones((2, 3))

# Create a NumPy array using arange
range_array = np.arange(10)

# Create a NumPy array using linspace
linspace_array = np.linspace(0, 10, 5)

# Print each created array
print("Array from list:")
print(array_from_list)

print("\nZeros array:")
print(zeros_array)

print("\nOnes array:")
print(ones_array)

print("\nRange array:")
print(range_array)

print("\nLinspace array:")
print(linspace_array)

Array from list:
[1 2 3 4 5]

Zeros array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones array:
[[1. 1. 1.]
 [1. 1. 1.]]

Range array:
[0 1 2 3 4 5 6 7 8 9]

Linspace array:
[ 0.   2.5  5.   7.5 10. ]


## Array attributes

### Subtask:
Show how to access important attributes of arrays (e.g., shape, dtype, size, ndim).


**Reasoning**:
Define a sample NumPy array and then access and print its shape, dtype, size, and ndim attributes as requested by the subtask.



In [3]:
# Define a sample NumPy array
sample_array = np.array([[1, 2, 3], [4, 5, 6]])

# Access and print the shape attribute
print("Shape of the array:", sample_array.shape)

# Access and print the dtype attribute
print("Data type of the array:", sample_array.dtype)

# Access and print the size attribute
print("Total number of elements in the array:", sample_array.size)

# Access and print the ndim attribute
print("Number of dimensions of the array:", sample_array.ndim)

Shape of the array: (2, 3)
Data type of the array: int64
Total number of elements in the array: 6
Number of dimensions of the array: 2


## Array indexing and slicing

### Subtask:
Illustrate how to access and modify elements or subarrays using indexing and slicing.


**Reasoning**:
The subtask requires demonstrating array indexing and slicing, including accessing and modifying elements and subarrays. This can be done in a single code block by creating a sample array and then performing the specified operations sequentially, printing the array after each step.



In [4]:
# Create a sample 2D NumPy array (e.g., a 3x3 array).
sample_array = np.array([[10, 11, 12],
                         [13, 14, 15],
                         [16, 17, 18]])
print("Original array:")
print(sample_array)
print("-" * 20)

# Demonstrate accessing a single element using integer indexing.
element = sample_array[1, 2] # Accessing element at row 1, column 2 (value 15)
print("Accessing single element at [1, 2]:", element)
print("-" * 20)

# Demonstrate accessing a row using slicing.
row = sample_array[0, :] # Accessing the first row
print("Accessing the first row using slicing sample_array[0, :]:")
print(row)
print("-" * 20)

# Demonstrate accessing a column using slicing.
column = sample_array[:, 1] # Accessing the second column
print("Accessing the second column using slicing sample_array[:, 1]:")
print(column)
print("-" * 20)

# Demonstrate accessing a subarray using slicing.
subarray = sample_array[0:2, 1:3] # Accessing a 2x2 subarray
print("Accessing a subarray using slicing sample_array[0:2, 1:3]:")
print(subarray)
print("-" * 20)

# Demonstrate modifying an element using indexing.
sample_array[2, 0] = 99 # Modify the element at row 2, column 0
print("Array after modifying element at [2, 0] to 99:")
print(sample_array)
print("-" * 20)

# Demonstrate modifying a subarray using slicing.
sample_array[0:2, 0:2] = [[100, 101], [102, 103]] # Modify the top-left 2x2 subarray
print("Array after modifying a subarray using slicing sample_array[0:2, 0:2]:")
print(sample_array)
print("-" * 20)

Original array:
[[10 11 12]
 [13 14 15]
 [16 17 18]]
--------------------
Accessing single element at [1, 2]: 15
--------------------
Accessing the first row using slicing sample_array[0, :]:
[10 11 12]
--------------------
Accessing the second column using slicing sample_array[:, 1]:
[11 14 17]
--------------------
Accessing a subarray using slicing sample_array[0:2, 1:3]:
[[11 12]
 [14 15]]
--------------------
Array after modifying element at [2, 0] to 99:
[[10 11 12]
 [13 14 15]
 [99 17 18]]
--------------------
Array after modifying a subarray using slicing sample_array[0:2, 0:2]:
[[100 101  12]
 [102 103  15]
 [ 99  17  18]]
--------------------


## Array operations

### Subtask:
Demonstrate common mathematical and logical operations on arrays (e.g., arithmetic operations, broadcasting, universal functions).


**Reasoning**:
The subtask requires demonstrating mathematical and logical operations on arrays. This involves creating sample arrays, performing arithmetic and logical operations, and demonstrating broadcasting and universal functions. All these steps can be included in a single code block.



In [5]:
# 1. Create two sample NumPy arrays of compatible shapes for arithmetic operations.
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("-" * 20)

# 2. Perform and print the results of basic arithmetic operations.
print("Addition (array1 + array2):")
print(array1 + array2)
print("\nSubtraction (array1 - array2):")
print(array1 - array2)
print("\nMultiplication (array1 * array2):")
print(array1 * array2) # Element-wise multiplication
print("\nDivision (array1 / array2):")
print(array1 / array2)
print("-" * 20)

# 3. Create a NumPy array and a scalar value.
array_for_broadcasting = np.array([[10, 20, 30], [40, 50, 60]])
scalar_value = 5
print("Array for broadcasting:")
print(array_for_broadcasting)
print("\nScalar value:", scalar_value)
print("-" * 20)

# 4. Demonstrate and print the results of broadcasting operations.
print("Broadcasting (array_for_broadcasting + scalar_value):")
print(array_for_broadcasting + scalar_value)
print("-" * 20)

# 5. Create a NumPy array and demonstrate the use of a universal function.
array_for_ufunc = np.array([1, 4, 9, 16])
print("Array for universal function:")
print(array_for_ufunc)
print("\nApplying np.sqrt():")
print(np.sqrt(array_for_ufunc))
print("-" * 20)

# 6. Create two NumPy arrays for logical operations.
array_logical1 = np.array([True, False, True, False])
array_logical2 = np.array([True, True, False, False])
array_comparison = np.array([10, 20, 30, 40])
scalar_comparison = 25
print("Logical Array 1:", array_logical1)
print("Logical Array 2:", array_logical2)
print("Comparison Array:", array_comparison)
print("Comparison Scalar:", scalar_comparison)
print("-" * 20)


# 7. Perform and print the results of logical operations.
print("Logical AND (array_logical1 & array_logical2):")
print(array_logical1 & array_logical2)
print("\nLogical OR (array_logical1 | array_logical2):")
print(array_logical1 | array_logical2)
print("\nComparison (array_comparison > scalar_comparison):")
print(array_comparison > scalar_comparison)
print("\nComparison (array_comparison == 20):")
print(array_comparison == 20)

Array 1:
[[1 2]
 [3 4]]

Array 2:
[[5 6]
 [7 8]]
--------------------
Addition (array1 + array2):
[[ 6  8]
 [10 12]]

Subtraction (array1 - array2):
[[-4 -4]
 [-4 -4]]

Multiplication (array1 * array2):
[[ 5 12]
 [21 32]]

Division (array1 / array2):
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
--------------------
Array for broadcasting:
[[10 20 30]
 [40 50 60]]

Scalar value: 5
--------------------
Broadcasting (array_for_broadcasting + scalar_value):
[[15 25 35]
 [45 55 65]]
--------------------
Array for universal function:
[ 1  4  9 16]

Applying np.sqrt():
[1. 2. 3. 4.]
--------------------
Logical Array 1: [ True False  True False]
Logical Array 2: [ True  True False False]
Comparison Array: [10 20 30 40]
Comparison Scalar: 25
--------------------
Logical AND (array_logical1 & array_logical2):
[ True False False False]

Logical OR (array_logical1 | array_logical2):
[ True  True  True False]

Comparison (array_comparison > scalar_comparison):
[False False  True  True]

Comp

## Array manipulation

### Subtask:
Show how to reshape, stack, split, and transpose arrays.


**Reasoning**:
The subtask requires demonstrating reshape, stack, split, and transpose operations. This involves creating arrays, performing these operations, and printing the results, which can all be done within a single code block.



In [6]:
# 1. Create a sample 1D NumPy array.
array_1d = np.arange(12)
print("Original 1D array:")
print(array_1d)
print("-" * 20)

# 2. Reshape the 1D array into a 2D array and print the result.
# Reshape into a 3x4 array
array_2d_reshaped = array_1d.reshape((3, 4))
print("Reshaped 2D array (3x4):")
print(array_2d_reshaped)
print("-" * 20)

# 3. Create two sample 2D NumPy arrays of compatible shapes for stacking.
array_stack1 = np.array([[1, 2, 3], [4, 5, 6]])
array_stack2 = np.array([[7, 8, 9], [10, 11, 12]])
print("Array for stacking 1:")
print(array_stack1)
print("\nArray for stacking 2:")
print(array_stack2)
print("-" * 20)

# 4. Vertically stack the two 2D arrays and print the result.
vstacked_array = np.vstack((array_stack1, array_stack2))
print("Vertically stacked array:")
print(vstacked_array)
print("-" * 20)

# 5. Horizontally stack the two 2D arrays and print the result.
hstacked_array = np.hstack((array_stack1, array_stack2))
print("Horizontally stacked array:")
print(hstacked_array)
print("-" * 20)

# 6. Create a sample 1D or 2D NumPy array to demonstrate splitting.
array_to_split = np.arange(16).reshape((4, 4))
print("Array to split:")
print(array_to_split)
print("-" * 20)

# 7. Split the array into multiple smaller arrays (e.g., into 3 equal parts or at specific indices) and print the resulting arrays.
# Split into 4 equal parts along rows
split_arrays_rows = np.vsplit(array_to_split, 4)
print("Array split into 4 parts along rows:")
for i, arr in enumerate(split_arrays_rows):
    print(f"Part {i+1}:\n{arr}")
print("-" * 20)

# Split into 2 equal parts along columns
split_arrays_cols = np.hsplit(array_to_split, 2)
print("Array split into 2 parts along columns:")
for i, arr in enumerate(split_arrays_cols):
    print(f"Part {i+1}:\n{arr}")
print("-" * 20)


# 8. Create a sample 2D NumPy array to demonstrate transposing.
array_to_transpose = np.array([[1, 2, 3], [4, 5, 6]])
print("Array to transpose:")
print(array_to_transpose)
print("-" * 20)

# 9. Transpose the 2D array and print the result.
transposed_array = array_to_transpose.T
print("Transposed array:")
print(transposed_array)

Original 1D array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
--------------------
Reshaped 2D array (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------
Array for stacking 1:
[[1 2 3]
 [4 5 6]]

Array for stacking 2:
[[ 7  8  9]
 [10 11 12]]
--------------------
Vertically stacked array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
--------------------
Horizontally stacked array:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
--------------------
Array to split:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
--------------------
Array split into 4 parts along rows:
Part 1:
[[0 1 2 3]]
Part 2:
[[4 5 6 7]]
Part 3:
[[ 8  9 10 11]]
Part 4:
[[12 13 14 15]]
--------------------
Array split into 2 parts along columns:
Part 1:
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Part 2:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
--------------------
Array to transpose:
[[1 2 3]
 [4 5 6]]
--------------------
Transposed array:
[[1 4]
 [2 5]
 [3 6]]


## Linear algebra operations

### Subtask:
Introduce basic linear algebra operations available in NumPy (e.g., dot product, matrix multiplication, solving linear equations).


**Reasoning**:
The subtask requires demonstrating basic linear algebra operations using NumPy. This involves creating matrices, performing dot product and matrix multiplication, and solving a linear system. These operations can be grouped into a single code block for clarity and efficiency.



In [7]:
# 1. Create two sample NumPy arrays representing matrices suitable for matrix multiplication.
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("-" * 20)

# 2. Perform and print the result of the dot product of the two arrays using np.dot().
# For 2D arrays (matrices), np.dot is matrix multiplication.
dot_product_result = np.dot(matrix1, matrix2)
print("Dot product (matrix multiplication) using np.dot():")
print(dot_product_result)
print("-" * 20)

# 3. Perform and print the result of matrix multiplication of the two arrays using the @ operator or np.matmul().
# Using the @ operator (preferred for matrix multiplication in Python 3.5+)
matrix_multiplication_result_at = matrix1 @ matrix2
print("Matrix multiplication using the @ operator:")
print(matrix_multiplication_result_at)

# Using np.matmul()
matrix_multiplication_result_matmul = np.matmul(matrix1, matrix2)
print("\nMatrix multiplication using np.matmul():")
print(matrix_multiplication_result_matmul)
print("-" * 20)

# 4. Create a square NumPy array representing a matrix and a 1D NumPy array representing a vector for demonstrating solving a linear system.
# Consider the linear system Ax = b, where A is the square_matrix and b is the vector.
square_matrix = np.array([[3, 1], [1, 2]])
vector = np.array([9, 8])
print("Square matrix (A):")
print(square_matrix)
print("\nVector (b):")
print(vector)
print("-" * 20)

# 5. Solve the linear system using np.linalg.solve() and print the solution vector.
# This solves for x in the equation Ax = b
solution_vector = np.linalg.solve(square_matrix, vector)
print("Solution vector (x) for Ax = b using np.linalg.solve():")
print(solution_vector)

Matrix 1:
[[1 2]
 [3 4]]

Matrix 2:
[[5 6]
 [7 8]]
--------------------
Dot product (matrix multiplication) using np.dot():
[[19 22]
 [43 50]]
--------------------
Matrix multiplication using the @ operator:
[[19 22]
 [43 50]]

Matrix multiplication using np.matmul():
[[19 22]
 [43 50]]
--------------------
Square matrix (A):
[[3 1]
 [1 2]]

Vector (b):
[9 8]
--------------------
Solution vector (x) for Ax = b using np.linalg.solve():
[2. 3.]
